name: Daily Currency Updater

on:
  schedule:
    - cron: '0 0 * * *'  # Runs at 00:00 UTC every day
  workflow_dispatch:

jobs:
  update-currency:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python Selenium Action
        uses: MarketingPipeline/Python-Selenium-Action@v1
        with:
          args: pip install -r requirements.txt && python currency_updater.py
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}